apiVersion: v2
name: muzayede
description: Muzayede Auction Platform — Helm Chart for all microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Muzayede Platform Team
    email: devops@muzayede.com
keywords:
  - auction
  - muzayede
  - microservices
home: https://github.com/muzayede/muzayede-platform
sources:
  - https://github.com/muzayede/muzayede-platform
