/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FractionalOwnership {
  export type FractionalListingStruct = {
    nftContract: AddressLike;
    nftTokenId: BigNumberish;
    totalShares: BigNumberish;
    availableShares: BigNumberish;
    pricePerShare: BigNumberish;
    originalOwner: AddressLike;
    isActive: boolean;
    createdAt: BigNumberish;
    minimumHoldingPeriod: BigNumberish;
    totalDividendsDistributed: BigNumberish;
  };

  export type FractionalListingStructOutput = [
    nftContract: string,
    nftTokenId: bigint,
    totalShares: bigint,
    availableShares: bigint,
    pricePerShare: bigint,
    originalOwner: string,
    isActive: boolean,
    createdAt: bigint,
    minimumHoldingPeriod: bigint,
    totalDividendsDistributed: bigint
  ] & {
    nftContract: string;
    nftTokenId: bigint;
    totalShares: bigint;
    availableShares: bigint;
    pricePerShare: bigint;
    originalOwner: string;
    isActive: boolean;
    createdAt: bigint;
    minimumHoldingPeriod: bigint;
    totalDividendsDistributed: bigint;
  };
}

export interface FractionalOwnershipInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "accumulatedRevenue"
      | "balanceOf"
      | "balanceOfBatch"
      | "buySharesFromHolder"
      | "canSell"
      | "claimDividend"
      | "claimedDividends"
      | "closeListing"
      | "createListing"
      | "cumulativeDividendPerShare"
      | "delistShares"
      | "distributeDividend"
      | "getListing"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isApprovedForAll"
      | "listSharesForSale"
      | "listings"
      | "pendingDividend"
      | "purchaseShares"
      | "purchaseTimestamp"
      | "renounceRole"
      | "revokeRole"
      | "safeBatchTransferFrom"
      | "safeTransferFrom"
      | "setApprovalForAll"
      | "sharesForSale"
      | "soldShares"
      | "supportsInterface"
      | "uri"
      | "userDividendSnapshot"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApprovalForAll"
      | "DividendClaimed"
      | "DividendDistributed"
      | "FractionCreated"
      | "ListingClosed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SharesDelistedFromSale"
      | "SharesListedForSale"
      | "SharesPurchased"
      | "SharesSold"
      | "TransferBatch"
      | "TransferSingle"
      | "URI"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "buySharesFromHolder",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canSell",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDividend",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedDividends",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createListing",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cumulativeDividendPerShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delistShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeDividend",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listSharesForSale",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingDividend",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseShares",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTimestamp",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sharesForSale",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "soldShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "userDividendSnapshot",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buySharesFromHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canSell", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedDividends",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cumulativeDividendPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delistShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listSharesForSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharesForSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "soldShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userDividendSnapshot",
    data: BytesLike
  ): Result;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    account: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    account: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    account: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendClaimedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    holder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [listingId: bigint, holder: string, amount: bigint];
  export interface OutputObject {
    listingId: bigint;
    holder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendDistributedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    amount: BigNumberish,
    totalDividendsToDate: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    amount: bigint,
    totalDividendsToDate: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    amount: bigint;
    totalDividendsToDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FractionCreatedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    nftContract: AddressLike,
    nftTokenId: BigNumberish,
    totalShares: BigNumberish,
    pricePerShare: BigNumberish,
    minimumHoldingPeriod: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    nftContract: string,
    nftTokenId: bigint,
    totalShares: bigint,
    pricePerShare: bigint,
    minimumHoldingPeriod: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    nftContract: string;
    nftTokenId: bigint;
    totalShares: bigint;
    pricePerShare: bigint;
    minimumHoldingPeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingClosedEvent {
  export type InputTuple = [listingId: BigNumberish, closedBy: AddressLike];
  export type OutputTuple = [listingId: bigint, closedBy: string];
  export interface OutputObject {
    listingId: bigint;
    closedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesDelistedFromSaleEvent {
  export type InputTuple = [listingId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [listingId: bigint, seller: string];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesListedForSaleEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    seller: AddressLike,
    quantity: BigNumberish,
    pricePerShare: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    seller: string,
    quantity: bigint,
    pricePerShare: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
    quantity: bigint;
    pricePerShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesPurchasedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    buyer: AddressLike,
    shares: BigNumberish,
    totalPaid: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    buyer: string,
    shares: bigint,
    totalPaid: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    buyer: string;
    shares: bigint;
    totalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesSoldEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    seller: AddressLike,
    buyer: AddressLike,
    shares: BigNumberish,
    totalPaid: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    seller: string,
    buyer: string,
    shares: bigint,
    totalPaid: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
    buyer: string;
    shares: bigint;
    totalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferBatchEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    ids: BigNumberish[],
    values: BigNumberish[]
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    ids: bigint[],
    values: bigint[]
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    ids: bigint[];
    values: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferSingleEvent {
  export type InputTuple = [
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    id: BigNumberish,
    value: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    from: string,
    to: string,
    id: bigint,
    value: bigint
  ];
  export interface OutputObject {
    operator: string;
    from: string;
    to: string;
    id: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace URIEvent {
  export type InputTuple = [value: string, id: BigNumberish];
  export type OutputTuple = [value: string, id: bigint];
  export interface OutputObject {
    value: string;
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FractionalOwnership extends BaseContract {
  connect(runner?: ContractRunner | null): FractionalOwnership;
  waitForDeployment(): Promise<this>;

  interface: FractionalOwnershipInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  accumulatedRevenue: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  balanceOf: TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;

  balanceOfBatch: TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;

  buySharesFromHolder: TypedContractMethod<
    [listingId: BigNumberish, seller: AddressLike, shares: BigNumberish],
    [void],
    "payable"
  >;

  canSell: TypedContractMethod<
    [listingId: BigNumberish, holder: AddressLike],
    [boolean],
    "view"
  >;

  claimDividend: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimedDividends: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  closeListing: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createListing: TypedContractMethod<
    [
      nftContract: AddressLike,
      nftTokenId: BigNumberish,
      totalShares: BigNumberish,
      pricePerShare: BigNumberish,
      minimumHoldingPeriod: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  cumulativeDividendPerShare: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  delistShares: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeDividend: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "payable"
  >;

  getListing: TypedContractMethod<
    [listingId: BigNumberish],
    [FractionalOwnership.FractionalListingStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  listSharesForSale: TypedContractMethod<
    [
      listingId: BigNumberish,
      quantity: BigNumberish,
      askPricePerShare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        nftContract: string;
        nftTokenId: bigint;
        totalShares: bigint;
        availableShares: bigint;
        pricePerShare: bigint;
        originalOwner: string;
        isActive: boolean;
        createdAt: bigint;
        minimumHoldingPeriod: bigint;
        totalDividendsDistributed: bigint;
      }
    ],
    "view"
  >;

  pendingDividend: TypedContractMethod<
    [listingId: BigNumberish, holder: AddressLike],
    [bigint],
    "view"
  >;

  purchaseShares: TypedContractMethod<
    [listingId: BigNumberish, shares: BigNumberish],
    [void],
    "payable"
  >;

  purchaseTimestamp: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  safeBatchTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  safeTransferFrom: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  sharesForSale: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        quantity: bigint;
        pricePerShare: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  soldShares: TypedContractMethod<[listingId: BigNumberish], [bigint], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  uri: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  userDividendSnapshot: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accumulatedRevenue"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<
    [account: AddressLike, id: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOfBatch"
  ): TypedContractMethod<
    [accounts: AddressLike[], ids: BigNumberish[]],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "buySharesFromHolder"
  ): TypedContractMethod<
    [listingId: BigNumberish, seller: AddressLike, shares: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "canSell"
  ): TypedContractMethod<
    [listingId: BigNumberish, holder: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimDividend"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedDividends"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeListing"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createListing"
  ): TypedContractMethod<
    [
      nftContract: AddressLike,
      nftTokenId: BigNumberish,
      totalShares: BigNumberish,
      pricePerShare: BigNumberish,
      minimumHoldingPeriod: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cumulativeDividendPerShare"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "delistShares"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeDividend"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [listingId: BigNumberish],
    [FractionalOwnership.FractionalListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [account: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "listSharesForSale"
  ): TypedContractMethod<
    [
      listingId: BigNumberish,
      quantity: BigNumberish,
      askPricePerShare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        bigint
      ] & {
        nftContract: string;
        nftTokenId: bigint;
        totalShares: bigint;
        availableShares: bigint;
        pricePerShare: bigint;
        originalOwner: string;
        isActive: boolean;
        createdAt: bigint;
        minimumHoldingPeriod: bigint;
        totalDividendsDistributed: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingDividend"
  ): TypedContractMethod<
    [listingId: BigNumberish, holder: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchaseShares"
  ): TypedContractMethod<
    [listingId: BigNumberish, shares: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "purchaseTimestamp"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeBatchTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      ids: BigNumberish[],
      values: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      id: BigNumberish,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sharesForSale"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        quantity: bigint;
        pricePerShare: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "soldShares"
  ): TypedContractMethod<[listingId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "uri"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "userDividendSnapshot"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "DividendClaimed"
  ): TypedContractEvent<
    DividendClaimedEvent.InputTuple,
    DividendClaimedEvent.OutputTuple,
    DividendClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DividendDistributed"
  ): TypedContractEvent<
    DividendDistributedEvent.InputTuple,
    DividendDistributedEvent.OutputTuple,
    DividendDistributedEvent.OutputObject
  >;
  getEvent(
    key: "FractionCreated"
  ): TypedContractEvent<
    FractionCreatedEvent.InputTuple,
    FractionCreatedEvent.OutputTuple,
    FractionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ListingClosed"
  ): TypedContractEvent<
    ListingClosedEvent.InputTuple,
    ListingClosedEvent.OutputTuple,
    ListingClosedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SharesDelistedFromSale"
  ): TypedContractEvent<
    SharesDelistedFromSaleEvent.InputTuple,
    SharesDelistedFromSaleEvent.OutputTuple,
    SharesDelistedFromSaleEvent.OutputObject
  >;
  getEvent(
    key: "SharesListedForSale"
  ): TypedContractEvent<
    SharesListedForSaleEvent.InputTuple,
    SharesListedForSaleEvent.OutputTuple,
    SharesListedForSaleEvent.OutputObject
  >;
  getEvent(
    key: "SharesPurchased"
  ): TypedContractEvent<
    SharesPurchasedEvent.InputTuple,
    SharesPurchasedEvent.OutputTuple,
    SharesPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "SharesSold"
  ): TypedContractEvent<
    SharesSoldEvent.InputTuple,
    SharesSoldEvent.OutputTuple,
    SharesSoldEvent.OutputObject
  >;
  getEvent(
    key: "TransferBatch"
  ): TypedContractEvent<
    TransferBatchEvent.InputTuple,
    TransferBatchEvent.OutputTuple,
    TransferBatchEvent.OutputObject
  >;
  getEvent(
    key: "TransferSingle"
  ): TypedContractEvent<
    TransferSingleEvent.InputTuple,
    TransferSingleEvent.OutputTuple,
    TransferSingleEvent.OutputObject
  >;
  getEvent(
    key: "URI"
  ): TypedContractEvent<
    URIEvent.InputTuple,
    URIEvent.OutputTuple,
    URIEvent.OutputObject
  >;

  filters: {
    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "DividendClaimed(uint256,address,uint256)": TypedContractEvent<
      DividendClaimedEvent.InputTuple,
      DividendClaimedEvent.OutputTuple,
      DividendClaimedEvent.OutputObject
    >;
    DividendClaimed: TypedContractEvent<
      DividendClaimedEvent.InputTuple,
      DividendClaimedEvent.OutputTuple,
      DividendClaimedEvent.OutputObject
    >;

    "DividendDistributed(uint256,uint256,uint256)": TypedContractEvent<
      DividendDistributedEvent.InputTuple,
      DividendDistributedEvent.OutputTuple,
      DividendDistributedEvent.OutputObject
    >;
    DividendDistributed: TypedContractEvent<
      DividendDistributedEvent.InputTuple,
      DividendDistributedEvent.OutputTuple,
      DividendDistributedEvent.OutputObject
    >;

    "FractionCreated(uint256,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FractionCreatedEvent.InputTuple,
      FractionCreatedEvent.OutputTuple,
      FractionCreatedEvent.OutputObject
    >;
    FractionCreated: TypedContractEvent<
      FractionCreatedEvent.InputTuple,
      FractionCreatedEvent.OutputTuple,
      FractionCreatedEvent.OutputObject
    >;

    "ListingClosed(uint256,address)": TypedContractEvent<
      ListingClosedEvent.InputTuple,
      ListingClosedEvent.OutputTuple,
      ListingClosedEvent.OutputObject
    >;
    ListingClosed: TypedContractEvent<
      ListingClosedEvent.InputTuple,
      ListingClosedEvent.OutputTuple,
      ListingClosedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SharesDelistedFromSale(uint256,address)": TypedContractEvent<
      SharesDelistedFromSaleEvent.InputTuple,
      SharesDelistedFromSaleEvent.OutputTuple,
      SharesDelistedFromSaleEvent.OutputObject
    >;
    SharesDelistedFromSale: TypedContractEvent<
      SharesDelistedFromSaleEvent.InputTuple,
      SharesDelistedFromSaleEvent.OutputTuple,
      SharesDelistedFromSaleEvent.OutputObject
    >;

    "SharesListedForSale(uint256,address,uint256,uint256)": TypedContractEvent<
      SharesListedForSaleEvent.InputTuple,
      SharesListedForSaleEvent.OutputTuple,
      SharesListedForSaleEvent.OutputObject
    >;
    SharesListedForSale: TypedContractEvent<
      SharesListedForSaleEvent.InputTuple,
      SharesListedForSaleEvent.OutputTuple,
      SharesListedForSaleEvent.OutputObject
    >;

    "SharesPurchased(uint256,address,uint256,uint256)": TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;
    SharesPurchased: TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;

    "SharesSold(uint256,address,address,uint256,uint256)": TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;
    SharesSold: TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;

    "TransferBatch(address,address,address,uint256[],uint256[])": TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;
    TransferBatch: TypedContractEvent<
      TransferBatchEvent.InputTuple,
      TransferBatchEvent.OutputTuple,
      TransferBatchEvent.OutputObject
    >;

    "TransferSingle(address,address,address,uint256,uint256)": TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;
    TransferSingle: TypedContractEvent<
      TransferSingleEvent.InputTuple,
      TransferSingleEvent.OutputTuple,
      TransferSingleEvent.OutputObject
    >;

    "URI(string,uint256)": TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;
    URI: TypedContractEvent<
      URIEvent.InputTuple,
      URIEvent.OutputTuple,
      URIEvent.OutputObject
    >;
  };
}
