/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuctionNFT } from "./AuctionNFT";
export type { CollectorBadge } from "./CollectorBadge";
export type { FractionalOwnership } from "./FractionalOwnership";
